# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in package.json
RUN npm install

# Make port 3006 available to the world outside this container
EXPOSE 3006

# Command to run the app
CMD ["npm", "start"]
